# Generated by Django 3.2.4 on 2021-07-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='community',
            field=models.CharField(choices=[('C1', '미국'), ('C2', '일본'), ('C3', '캐나다')], default='C1', max_length=100),
        ),
    ]
